// Generated by npm run build.
window.__ModuleLoader__.load({
  id: "dsh-settings-scroll",
  factory: () => {
const name = 'settings-scroll';

const NAV = 'data-dsh-settings-scroll-nav';
const LIST = 'data-dsh-settings-scroll-list';
const STYLE_ID = 'dsh-settings-scroll-style';
const STYLE = `
[${NAV}] {
  min-height: 0 !important;
  overflow: hidden !important;
  padding-bottom: 12px !important;
}
[${NAV}] > :first-child { flex-shrink: 0 !important; }
[${LIST}] {
  flex: 1 1 0% !important;
  min-height: 0 !important;
  overflow-y: auto !important;
  overflow-x: hidden !important;
  overscroll-behavior-y: contain;
  scrollbar-gutter: stable;
  padding-bottom: 12px;
  scroll-padding-block: 4px;
}
[${LIST}] > button { flex-shrink: 0 !important; }
`;

/** Match the official settings shell without depending on CSS hash prefixes. */
function findSettingsLists(doc) {
  const matches = [];
  for (const dialog of doc.querySelectorAll('[role="dialog"][aria-modal="true"]')) {
    for (const nav of dialog.children) {
      if (nav.tagName !== 'NAV') continue;
      const [title, list] = nav.children;
      if (!title?.id || !list || !dialog.getAttribute('aria-labelledby')?.split(/\s+/).includes(title.id)) continue;
      if (![...list.classList].some(token => token.endsWith('_navList'))) continue;
      if (![...list.children].some(child => child.tagName === 'BUTTON')) continue;
      matches.push({ nav, list });
    }
  }
  return matches;
}

/** Reveal only within the list; never scroll the page or the settings content. */
function reveal(list, button) {
  const box = list.getBoundingClientRect();
  const item = button.getBoundingClientRect();
  const top = box.top + list.clientTop;
  const bottom = top + list.clientHeight;
  if (item.top < top) list.scrollTop -= top - item.top;
  else if (item.bottom > bottom) list.scrollTop += item.bottom - bottom;
}

function install(doc = document) {
  // The loader disposes the previous mount before applying a replacement.
  const style = doc.createElement('style');
  style.id = STYLE_ID;
  style.dataset.plugin = 'dsh-settings-scroll';
  style.textContent = STYLE;
  doc.head.append(style);
  const mounted = new Map();
  let disposed = false;
  let pending = false;

  const sync = () => {
    pending = false;
    if (disposed) return;
    const current = new Set();
    for (const { nav, list } of findSettingsLists(doc)) {
      current.add(list);
      if (!mounted.has(list)) {
        const oldNav = nav.getAttribute(NAV);
        const oldList = list.getAttribute(LIST);
        nav.setAttribute(NAV, '');
        list.setAttribute(LIST, '');
        const focus = event => {
          const button = event.target.closest?.('button');
          if (button?.parentElement === list) reveal(list, button);
        };
        const key = event => {
          if (event.defaultPrevented || event.altKey || event.ctrlKey || event.metaKey || event.shiftKey) return;
          const button = event.target.closest?.('button');
          if (button?.parentElement !== list) return;
          const buttons = [...list.children].filter(child => child.tagName === 'BUTTON' && !child.disabled && child.getClientRects().length);
          const index = buttons.indexOf(button);
          if (index < 0) return;
          let next;
          if (event.key === 'ArrowDown') next = Math.min(index + 1, buttons.length - 1);
          else if (event.key === 'ArrowUp') next = Math.max(index - 1, 0);
          else if (event.key === 'Home') next = 0;
          else if (event.key === 'End') next = buttons.length - 1;
          else return;
          event.preventDefault();
          buttons[next].focus({ preventScroll: true });
          reveal(list, buttons[next]);
        };
        list.addEventListener('focusin', focus);
        list.addEventListener('keydown', key);
        mounted.set(list, {
          active: null,
          cleanup() {
            list.removeEventListener('focusin', focus);
            list.removeEventListener('keydown', key);
            oldNav === null ? nav.removeAttribute(NAV) : nav.setAttribute(NAV, oldNav);
            oldList === null ? list.removeAttribute(LIST) : list.setAttribute(LIST, oldList);
          },
        });
      }
      const state = mounted.get(list);
      const active = list.querySelector(':scope > button[aria-current="true"]');
      if (state.active !== active) {
        state.active = active;
        if (active) reveal(list, active);
      }
    }
    for (const [list, state] of mounted) {
      if (!current.has(list)) {
        state.cleanup();
        mounted.delete(list);
      }
    }
  };
  const observer = new doc.defaultView.MutationObserver(() => {
    if (!pending) {
      pending = true;
      queueMicrotask(sync);
    }
  });
  observer.observe(doc.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['aria-current'] });
  sync();
  return () => {
    disposed = true;
    observer.disconnect();
    for (const state of mounted.values()) state.cleanup();
    mounted.clear();
    style.remove();
  };
}

/** Cordis owns the effect and removes styles, listeners and observers on unload. */
function apply(ctx) {
  ctx.effect(() => install(), 'settings-scroll: sidebar');
}

    return { name, apply };
  },
});
