import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
await mkdir(new URL('lib/', root), { recursive: true });
await copyFile(new URL('src/index.js', root), new URL('lib/index.js', root));
const source = await readFile(new URL('src/client.js', root), 'utf8');
// This dependency-free entry uses DSH's closure factory module protocol.
const body = source.replace(/^export /gm, '');
const output = `// Generated by npm run build.\nwindow.__ModuleLoader__.load({\n  id: ${JSON.stringify(manifest.name)},\n  factory: () => {\n${body}\n    return { name, apply };\n  },\n});\n`;
await writeFile(new URL('lib/client.js', root), output);
console.log(`Built ${manifest.name}@${manifest.version}`);
